INSERT INTO pricing_plans (id, name, price_per_m2, min_monthly_fee, price_per_carton, price_per_pallet, receiving_fee, picking_fee, packing_fee, return_fee, shipping_handling_fee, is_default) VALUES (1, 'الخطة الافتراضية', 450, 500, 15, 200, 25, 20, 15, 30, 10, 1);
INSERT INTO warehouses (id, name, code, address, total_capacity_m2) VALUES (1, 'المخزن الرئيسي - فيصل', 'WH-A', 'فيصل، الجيزة', 100);
INSERT INTO warehouses (id, name, code, address, total_capacity_m2) VALUES (2, 'مخزن مدينة نصر', 'WH-B', 'مدينة نصر، القاهرة', 60);
INSERT INTO warehouses (id, name, code, address, total_capacity_m2) VALUES (3, 'مخزن أكتوبر', 'WH-C', '6 أكتوبر، الجيزة', 80);
INSERT INTO zones (id, warehouse_id, name, code) VALUES (1, 1, 'منطقة 1', 'Z1');
INSERT INTO racks (id, zone_id, name, code) VALUES (1, 1, 'رف 11', 'R11');
INSERT INTO shelves (id, rack_id, name, code) VALUES (1, 1, 'شلف 1', 'R11-S1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (1, 1, 'صندوق 1', 'R11-S1-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (2, 1, 'صندوق 2', 'R11-S1-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (2, 1, 'شلف 2', 'R11-S2');
INSERT INTO bins (id, shelf_id, name, code) VALUES (3, 2, 'صندوق 1', 'R11-S2-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (4, 2, 'صندوق 2', 'R11-S2-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (3, 1, 'شلف 3', 'R11-S3');
INSERT INTO bins (id, shelf_id, name, code) VALUES (5, 3, 'صندوق 1', 'R11-S3-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (6, 3, 'صندوق 2', 'R11-S3-B2');
INSERT INTO racks (id, zone_id, name, code) VALUES (2, 1, 'رف 12', 'R12');
INSERT INTO shelves (id, rack_id, name, code) VALUES (4, 2, 'شلف 1', 'R12-S1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (7, 4, 'صندوق 1', 'R12-S1-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (8, 4, 'صندوق 2', 'R12-S1-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (5, 2, 'شلف 2', 'R12-S2');
INSERT INTO bins (id, shelf_id, name, code) VALUES (9, 5, 'صندوق 1', 'R12-S2-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (10, 5, 'صندوق 2', 'R12-S2-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (6, 2, 'شلف 3', 'R12-S3');
INSERT INTO bins (id, shelf_id, name, code) VALUES (11, 6, 'صندوق 1', 'R12-S3-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (12, 6, 'صندوق 2', 'R12-S3-B2');
INSERT INTO zones (id, warehouse_id, name, code) VALUES (2, 1, 'منطقة 2', 'Z2');
INSERT INTO racks (id, zone_id, name, code) VALUES (3, 2, 'رف 21', 'R21');
INSERT INTO shelves (id, rack_id, name, code) VALUES (7, 3, 'شلف 1', 'R21-S1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (13, 7, 'صندوق 1', 'R21-S1-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (14, 7, 'صندوق 2', 'R21-S1-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (8, 3, 'شلف 2', 'R21-S2');
INSERT INTO bins (id, shelf_id, name, code) VALUES (15, 8, 'صندوق 1', 'R21-S2-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (16, 8, 'صندوق 2', 'R21-S2-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (9, 3, 'شلف 3', 'R21-S3');
INSERT INTO bins (id, shelf_id, name, code) VALUES (17, 9, 'صندوق 1', 'R21-S3-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (18, 9, 'صندوق 2', 'R21-S3-B2');
INSERT INTO racks (id, zone_id, name, code) VALUES (4, 2, 'رف 22', 'R22');
INSERT INTO shelves (id, rack_id, name, code) VALUES (10, 4, 'شلف 1', 'R22-S1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (19, 10, 'صندوق 1', 'R22-S1-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (20, 10, 'صندوق 2', 'R22-S1-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (11, 4, 'شلف 2', 'R22-S2');
INSERT INTO bins (id, shelf_id, name, code) VALUES (21, 11, 'صندوق 1', 'R22-S2-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (22, 11, 'صندوق 2', 'R22-S2-B2');
INSERT INTO shelves (id, rack_id, name, code) VALUES (12, 4, 'شلف 3', 'R22-S3');
INSERT INTO bins (id, shelf_id, name, code) VALUES (23, 12, 'صندوق 1', 'R22-S3-B1');
INSERT INTO bins (id, shelf_id, name, code) VALUES (24, 12, 'صندوق 2', 'R22-S3-B2');
INSERT INTO users (id, email, password_hash, name, role) VALUES (1, 'superadmin@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'Super Admin', 'SUPER_ADMIN');
INSERT INTO users (id, email, password_hash, name, role) VALUES (2, 'admin@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'Admin', 'ADMIN');
INSERT INTO users (id, email, password_hash, name, role) VALUES (3, 'employee@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'Warehouse Employee', 'WAREHOUSE_EMPLOYEE');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (1, 'متجر تجربة 1', 'إلكترونيات', '0100000001', '0100000001', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (4, 'صاحب متجر تجربة 1', 'customer@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 1);
UPDATE customers SET user_id = 4 WHERE id = 1;
INSERT INTO storage_allocations (customer_id, warehouse_id, allocated_m2, used_m2, monthly_fee, status) VALUES (1, 1, 5, 3, 2250, 'active');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (2, 'متجر تجربة 2', 'مستحضرات تجميل', '0100000002', '0100000002', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (5, 'صاحب متجر تجربة 2', 'customer2@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 2);
UPDATE customers SET user_id = 5 WHERE id = 2;
INSERT INTO storage_allocations (customer_id, warehouse_id, allocated_m2, used_m2, monthly_fee, status) VALUES (2, 1, 10, 6, 4500, 'active');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (3, 'متجر تجربة 3', 'أحذية', '0100000003', '0100000003', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (6, 'صاحب متجر تجربة 3', 'customer3@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 3);
UPDATE customers SET user_id = 6 WHERE id = 3;
INSERT INTO storage_allocations (customer_id, warehouse_id, allocated_m2, used_m2, monthly_fee, status) VALUES (3, 1, 15, 9, 6750, 'active');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (4, 'متجر تجربة 4', 'إكسسوارات', '0100000004', '0100000004', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (7, 'صاحب متجر تجربة 4', 'customer4@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 4);
UPDATE customers SET user_id = 7 WHERE id = 4;
INSERT INTO storage_allocations (customer_id, warehouse_id, allocated_m2, used_m2, monthly_fee, status) VALUES (4, 1, 20, 12, 9000, 'active');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (5, 'متجر تجربة 5', 'ملابس', '0100000005', '0100000005', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (8, 'صاحب متجر تجربة 5', 'customer5@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 5);
UPDATE customers SET user_id = 8 WHERE id = 5;
INSERT INTO storage_allocations (customer_id, warehouse_id, allocated_m2, used_m2, monthly_fee, status) VALUES (5, 1, 8, 5, 3600, 'active');
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (6, 'متجر تجربة 6', 'إلكترونيات', '0100000006', '0100000006', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (9, 'صاحب متجر تجربة 6', 'customer6@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 6);
UPDATE customers SET user_id = 9 WHERE id = 6;
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (7, 'متجر تجربة 7', 'مستحضرات تجميل', '0100000007', '0100000007', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (10, 'صاحب متجر تجربة 7', 'customer7@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 7);
UPDATE customers SET user_id = 10 WHERE id = 7;
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (8, 'متجر تجربة 8', 'أحذية', '0100000008', '0100000008', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (11, 'صاحب متجر تجربة 8', 'customer8@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 8);
UPDATE customers SET user_id = 11 WHERE id = 8;
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (9, 'متجر تجربة 9', 'إكسسوارات', '0100000009', '0100000009', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (12, 'صاحب متجر تجربة 9', 'customer9@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 9);
UPDATE customers SET user_id = 12 WHERE id = 9;
INSERT INTO customers (id, company_name, business_type, phone, whatsapp, address, status) VALUES (10, 'متجر تجربة 10', 'ملابس', '01000000010', '01000000010', 'القاهرة، مصر', 'active');
INSERT INTO users (id, name, email, password_hash, role, customer_id) VALUES (13, 'صاحب متجر تجربة 10', 'customer10@demo.com', '$2b$10$ZRi3G3DONLxP4jtgHZLfEum//t9MVDdZ0aefSiLGmKGFF9NijS.ge', 'CUSTOMER', 10);
UPDATE customers SET user_id = 13 WHERE id = 10;
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (1, 2, 'SKU-1001', '6200000001001', 'منتج تجريبي 1', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.30000000000000004, '20x15x10 cm', 2);
UPDATE products SET quantity = 21 WHERE id = 1;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (1, 'IN', 21, 0, 21, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (2, 3, 'SKU-1002', '6200000001002', 'منتج تجريبي 2', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.2, '20x15x10 cm', 3);
UPDATE products SET quantity = 22 WHERE id = 2;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (2, 'IN', 22, 0, 22, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (3, 4, 'SKU-1003', '6200000001003', 'منتج تجريبي 3', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.2000000000000002, '20x15x10 cm', 4);
UPDATE products SET quantity = 23 WHERE id = 3;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (3, 'IN', 23, 0, 23, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (4, 5, 'SKU-1004', '6200000001004', 'منتج تجريبي 4', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 5);
UPDATE products SET quantity = 24 WHERE id = 4;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (4, 'IN', 24, 0, 24, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (5, 1, 'SKU-1005', '6200000001005', 'منتج تجريبي 5', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 6);
UPDATE products SET quantity = 25 WHERE id = 5;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (5, 'IN', 25, 0, 25, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (6, 2, 'SKU-1006', '6200000001006', 'منتج تجريبي 6', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.1, '20x15x10 cm', 7);
UPDATE products SET quantity = 26 WHERE id = 6;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (6, 'IN', 26, 0, 26, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (7, 3, 'SKU-1007', '6200000001007', 'منتج تجريبي 7', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 2, '20x15x10 cm', 8);
UPDATE products SET quantity = 27 WHERE id = 7;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (7, 'IN', 27, 0, 27, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (8, 4, 'SKU-1008', '6200000001008', 'منتج تجريبي 8', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 9);
UPDATE products SET quantity = 28 WHERE id = 8;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (8, 'IN', 28, 0, 28, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (9, 5, 'SKU-1009', '6200000001009', 'منتج تجريبي 9', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1, '20x15x10 cm', 10);
UPDATE products SET quantity = 29 WHERE id = 9;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (9, 'IN', 29, 0, 29, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (10, 1, 'SKU-1010', '6200000001010', 'منتج تجريبي 10', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 2, '20x15x10 cm', 11);
UPDATE products SET quantity = 30 WHERE id = 10;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (10, 'IN', 30, 0, 30, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (11, 2, 'SKU-1011', '6200000001011', 'منتج تجريبي 11', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.2, '20x15x10 cm', 12);
UPDATE products SET quantity = 31 WHERE id = 11;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (11, 'IN', 31, 0, 31, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (12, 3, 'SKU-1012', '6200000001012', 'منتج تجريبي 12', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.7999999999999999, '20x15x10 cm', 13);
UPDATE products SET quantity = 32 WHERE id = 12;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (12, 'IN', 32, 0, 32, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (13, 4, 'SKU-1013', '6200000001013', 'منتج تجريبي 13', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 2.1, '20x15x10 cm', 14);
UPDATE products SET quantity = 33 WHERE id = 13;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (13, 'IN', 33, 0, 33, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (14, 5, 'SKU-1014', '6200000001014', 'منتج تجريبي 14', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.4000000000000001, '20x15x10 cm', 15);
UPDATE products SET quantity = 34 WHERE id = 14;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (14, 'IN', 34, 0, 34, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (15, 1, 'SKU-1015', '6200000001015', 'منتج تجريبي 15', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.4000000000000001, '20x15x10 cm', 16);
UPDATE products SET quantity = 35 WHERE id = 15;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (15, 'IN', 35, 0, 35, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (16, 2, 'SKU-1016', '6200000001016', 'منتج تجريبي 16', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 2, '20x15x10 cm', 17);
UPDATE products SET quantity = 36 WHERE id = 16;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (16, 'IN', 36, 0, 36, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (17, 3, 'SKU-1017', '6200000001017', 'منتج تجريبي 17', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.30000000000000004, '20x15x10 cm', 18);
UPDATE products SET quantity = 37 WHERE id = 17;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (17, 'IN', 37, 0, 37, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (18, 4, 'SKU-1018', '6200000001018', 'منتج تجريبي 18', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.9, '20x15x10 cm', 19);
UPDATE products SET quantity = 38 WHERE id = 18;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (18, 'IN', 38, 0, 38, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (19, 5, 'SKU-1019', '6200000001019', 'منتج تجريبي 19', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.6, '20x15x10 cm', 20);
UPDATE products SET quantity = 39 WHERE id = 19;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (19, 'IN', 39, 0, 39, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (20, 1, 'SKU-1020', '6200000001020', 'منتج تجريبي 20', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.6, '20x15x10 cm', 21);
UPDATE products SET quantity = 40 WHERE id = 20;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (20, 'IN', 40, 0, 40, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (21, 2, 'SKU-1021', '6200000001021', 'منتج تجريبي 21', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.7999999999999999, '20x15x10 cm', 22);
UPDATE products SET quantity = 41 WHERE id = 21;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (21, 'IN', 41, 0, 41, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (22, 3, 'SKU-1022', '6200000001022', 'منتج تجريبي 22', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.4000000000000001, '20x15x10 cm', 23);
UPDATE products SET quantity = 42 WHERE id = 22;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (22, 'IN', 42, 0, 42, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (23, 4, 'SKU-1023', '6200000001023', 'منتج تجريبي 23', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 24);
UPDATE products SET quantity = 43 WHERE id = 23;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (23, 'IN', 43, 0, 43, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (24, 5, 'SKU-1024', '6200000001024', 'منتج تجريبي 24', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.2, '20x15x10 cm', 1);
UPDATE products SET quantity = 44 WHERE id = 24;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (24, 'IN', 44, 0, 44, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (25, 1, 'SKU-1025', '6200000001025', 'منتج تجريبي 25', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.7, '20x15x10 cm', 2);
UPDATE products SET quantity = 45 WHERE id = 25;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (25, 'IN', 45, 0, 45, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (26, 2, 'SKU-1026', '6200000001026', 'منتج تجريبي 26', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.7999999999999999, '20x15x10 cm', 3);
UPDATE products SET quantity = 46 WHERE id = 26;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (26, 'IN', 46, 0, 46, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (27, 3, 'SKU-1027', '6200000001027', 'منتج تجريبي 27', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 2, '20x15x10 cm', 4);
UPDATE products SET quantity = 47 WHERE id = 27;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (27, 'IN', 47, 0, 47, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (28, 4, 'SKU-1028', '6200000001028', 'منتج تجريبي 28', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.3, '20x15x10 cm', 5);
UPDATE products SET quantity = 48 WHERE id = 28;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (28, 'IN', 48, 0, 48, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (29, 5, 'SKU-1029', '6200000001029', 'منتج تجريبي 29', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 6);
UPDATE products SET quantity = 49 WHERE id = 29;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (29, 'IN', 49, 0, 49, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (30, 1, 'SKU-1030', '6200000001030', 'منتج تجريبي 30', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.2000000000000002, '20x15x10 cm', 7);
UPDATE products SET quantity = 20 WHERE id = 30;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (30, 'IN', 20, 0, 20, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (31, 2, 'SKU-1031', '6200000001031', 'منتج تجريبي 31', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1, '20x15x10 cm', 8);
UPDATE products SET quantity = 21 WHERE id = 31;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (31, 'IN', 21, 0, 21, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (32, 3, 'SKU-1032', '6200000001032', 'منتج تجريبي 32', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.1, '20x15x10 cm', 9);
UPDATE products SET quantity = 22 WHERE id = 32;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (32, 'IN', 22, 0, 22, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (33, 4, 'SKU-1033', '6200000001033', 'منتج تجريبي 33', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.5, '20x15x10 cm', 10);
UPDATE products SET quantity = 23 WHERE id = 33;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (33, 'IN', 23, 0, 23, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (34, 5, 'SKU-1034', '6200000001034', 'منتج تجريبي 34', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.2000000000000002, '20x15x10 cm', 11);
UPDATE products SET quantity = 24 WHERE id = 34;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (34, 'IN', 24, 0, 24, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (35, 1, 'SKU-1035', '6200000001035', 'منتج تجريبي 35', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.30000000000000004, '20x15x10 cm', 12);
UPDATE products SET quantity = 25 WHERE id = 35;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (35, 'IN', 25, 0, 25, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (36, 2, 'SKU-1036', '6200000001036', 'منتج تجريبي 36', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.30000000000000004, '20x15x10 cm', 13);
UPDATE products SET quantity = 26 WHERE id = 36;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (36, 'IN', 26, 0, 26, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (37, 3, 'SKU-1037', '6200000001037', 'منتج تجريبي 37', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.1, '20x15x10 cm', 14);
UPDATE products SET quantity = 27 WHERE id = 37;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (37, 'IN', 27, 0, 27, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (38, 4, 'SKU-1038', '6200000001038', 'منتج تجريبي 38', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1, '20x15x10 cm', 15);
UPDATE products SET quantity = 28 WHERE id = 38;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (38, 'IN', 28, 0, 28, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (39, 5, 'SKU-1039', '6200000001039', 'منتج تجريبي 39', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.4000000000000001, '20x15x10 cm', 16);
UPDATE products SET quantity = 29 WHERE id = 39;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (39, 'IN', 29, 0, 29, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (40, 1, 'SKU-1040', '6200000001040', 'منتج تجريبي 40', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.3, '20x15x10 cm', 17);
UPDATE products SET quantity = 30 WHERE id = 40;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (40, 'IN', 30, 0, 30, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (41, 2, 'SKU-1041', '6200000001041', 'منتج تجريبي 41', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.4, '20x15x10 cm', 18);
UPDATE products SET quantity = 31 WHERE id = 41;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (41, 'IN', 31, 0, 31, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (42, 3, 'SKU-1042', '6200000001042', 'منتج تجريبي 42', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.5, '20x15x10 cm', 19);
UPDATE products SET quantity = 32 WHERE id = 42;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (42, 'IN', 32, 0, 32, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (43, 4, 'SKU-1043', '6200000001043', 'منتج تجريبي 43', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.2, '20x15x10 cm', 20);
UPDATE products SET quantity = 33 WHERE id = 43;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (43, 'IN', 33, 0, 33, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (44, 5, 'SKU-1044', '6200000001044', 'منتج تجريبي 44', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.9000000000000001, '20x15x10 cm', 21);
UPDATE products SET quantity = 34 WHERE id = 44;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (44, 'IN', 34, 0, 34, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (45, 1, 'SKU-1045', '6200000001045', 'منتج تجريبي 45', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.5, '20x15x10 cm', 22);
UPDATE products SET quantity = 35 WHERE id = 45;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (45, 'IN', 35, 0, 35, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (46, 2, 'SKU-1046', '6200000001046', 'منتج تجريبي 46', 'ملابس حريمي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.7000000000000002, '20x15x10 cm', 23);
UPDATE products SET quantity = 36 WHERE id = 46;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (46, 'IN', 36, 0, 36, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (47, 3, 'SKU-1047', '6200000001047', 'منتج تجريبي 47', 'إكسسوارات', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.5, '20x15x10 cm', 24);
UPDATE products SET quantity = 37 WHERE id = 47;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (47, 'IN', 37, 0, 37, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (48, 4, 'SKU-1048', '6200000001048', 'منتج تجريبي 48', 'أحذية', 'منتج تجريبي لبيانات الاختبار', 0, 5, 1.2000000000000002, '20x15x10 cm', 1);
UPDATE products SET quantity = 38 WHERE id = 48;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (48, 'IN', 38, 0, 38, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (49, 5, 'SKU-1049', '6200000001049', 'منتج تجريبي 49', 'إلكترونيات صغيرة', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.7999999999999999, '20x15x10 cm', 2);
UPDATE products SET quantity = 39 WHERE id = 49;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (49, 'IN', 39, 0, 39, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO products (id, customer_id, sku, barcode, name, category, description, quantity, min_stock, unit_weight_kg, unit_dimensions, bin_id) VALUES (50, 1, 'SKU-1050', '6200000001050', 'منتج تجريبي 50', 'ملابس رجالي', 'منتج تجريبي لبيانات الاختبار', 0, 5, 0.30000000000000004, '20x15x10 cm', 3);
UPDATE products SET quantity = 40 WHERE id = 50;
INSERT INTO inventory_movements (product_id, type, quantity, previous_balance, new_balance, user_id, reason, reference_type) VALUES (50, 'IN', 40, 0, 40, 3, 'رصيد افتتاحي (بيانات تجريبية)', 'manual');
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (1, 'ORD-DEMO-1001', 2, 'picking', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (1, 1, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (2, 'ORD-DEMO-1002', 3, 'picked', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (2, 2, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (3, 'ORD-DEMO-1003', 4, 'packed', 'عنوان تجريبي، القاهرة', 'pending');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (3, 3, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (4, 'ORD-DEMO-1004', 5, 'shipped', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (4, 4, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (5, 'ORD-DEMO-1005', 1, 'delivered', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (5, 5, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (6, 'ORD-DEMO-1006', 2, 'pending', 'عنوان تجريبي، القاهرة', 'pending');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (6, 1, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (7, 'ORD-DEMO-1007', 3, 'picking', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (7, 2, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (8, 'ORD-DEMO-1008', 4, 'picked', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (8, 3, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (9, 'ORD-DEMO-1009', 5, 'packed', 'عنوان تجريبي، القاهرة', 'pending');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (9, 4, 2);
INSERT INTO orders (id, order_number, customer_id, status, shipping_address, payment_status) VALUES (10, 'ORD-DEMO-1010', 1, 'shipped', 'عنوان تجريبي، القاهرة', 'paid');
INSERT INTO order_items (order_id, product_id, quantity) VALUES (10, 5, 2);
INSERT INTO returns (id, return_number, order_id, customer_id, reason, status, decision) VALUES (1, 'RET-DEMO-101', 2, 3, 'مقاس غير مناسب', 'processed', 'return_to_stock');
INSERT INTO return_items (return_id, product_id, quantity) VALUES (1, 2, 1);
INSERT INTO returns (id, return_number, order_id, customer_id, reason, status, decision) VALUES (2, 'RET-DEMO-102', 3, 4, 'مقاس غير مناسب', 'processed', 'return_to_stock');
INSERT INTO return_items (return_id, product_id, quantity) VALUES (2, 3, 1);
INSERT INTO returns (id, return_number, order_id, customer_id, reason, status, decision) VALUES (3, 'RET-DEMO-103', 4, 5, 'مقاس غير مناسب', 'pending', NULL);
INSERT INTO return_items (return_id, product_id, quantity) VALUES (3, 4, 1);
INSERT INTO returns (id, return_number, order_id, customer_id, reason, status, decision) VALUES (4, 'RET-DEMO-104', 5, 1, 'مقاس غير مناسب', 'pending', NULL);
INSERT INTO return_items (return_id, product_id, quantity) VALUES (4, 5, 1);
INSERT INTO returns (id, return_number, order_id, customer_id, reason, status, decision) VALUES (5, 'RET-DEMO-105', 6, 2, 'مقاس غير مناسب', 'pending', NULL);
INSERT INTO return_items (return_id, product_id, quantity) VALUES (5, 1, 1);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (1, 'INV-DEMO-1001', 2, 1782471808, 1785063808, 620, 14, 86.8, 706.8, 'overdue', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (1, 'رسوم تخزين شهرية', 'storage', 1, 620);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (2, 'INV-DEMO-1002', 3, 1782471808, 1785063808, 740, 14, 103.6, 843.6, 'pending', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (2, 'رسوم تخزين شهرية', 'storage', 1, 740);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (3, 'INV-DEMO-1003', 4, 1782471808, 1785063808, 860, 14, 120.4, 980.4, 'pending', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (3, 'رسوم تخزين شهرية', 'storage', 1, 860);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (4, 'INV-DEMO-1004', 5, 1782471808, 1785063808, 980, 14, 137.2, 1117.2, 'paid', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (4, 'رسوم تخزين شهرية', 'storage', 1, 980);
INSERT INTO payments (invoice_id, amount, method, status) VALUES (4, 1117.2, 'bank_transfer', 'completed');
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (5, 'INV-DEMO-1005', 1, 1782471808, 1785063808, 1100, 14, 154, 1254, 'overdue', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (5, 'رسوم تخزين شهرية', 'storage', 1, 1100);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (6, 'INV-DEMO-1006', 2, 1782471808, 1785063808, 1220, 14, 170.8, 1390.8, 'pending', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (6, 'رسوم تخزين شهرية', 'storage', 1, 1220);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (7, 'INV-DEMO-1007', 3, 1782471808, 1785063808, 1340, 14, 187.6, 1527.6, 'pending', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (7, 'رسوم تخزين شهرية', 'storage', 1, 1340);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (8, 'INV-DEMO-1008', 4, 1782471808, 1785063808, 1460, 14, 204.4, 1664.4, 'paid', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (8, 'رسوم تخزين شهرية', 'storage', 1, 1460);
INSERT INTO payments (invoice_id, amount, method, status) VALUES (8, 1664.4, 'bank_transfer', 'completed');
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (9, 'INV-DEMO-1009', 5, 1782471808, 1785063808, 1580, 14, 221.2, 1801.2, 'overdue', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (9, 'رسوم تخزين شهرية', 'storage', 1, 1580);
INSERT INTO invoices (id, invoice_number, customer_id, period_start, period_end, subtotal, tax_rate, tax_amount, total, status, due_date) VALUES (10, 'INV-DEMO-1010', 1, 1782471808, 1785063808, 1700, 14, 238, 1938, 'pending', 1786359808);
INSERT INTO invoice_items (invoice_id, description, type, quantity, amount) VALUES (10, 'رسوم تخزين شهرية', 'storage', 1, 1700);
INSERT INTO leads (name, phone, business_type, required_space_m2, number_of_products, status) VALUES ('أحمد صاحب متجر أونلاين', '01099998888', 'ملابس', 10, 40, 'new');
INSERT INTO leads (name, phone, business_type, required_space_m2, number_of_products, status) VALUES ('سارة ستور', '01088887777', 'مستحضرات تجميل', 5, 20, 'contacted');
INSERT INTO settings (key, value) VALUES ('company_name', 'مساحة — Storage & Fulfillment');
INSERT INTO settings (key, value) VALUES ('currency', 'EGP');
INSERT INTO settings (key, value) VALUES ('default_tax_rate', '14');
